# Generated by Django 4.2.23 on 2025-11-27 21:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookclub_bookclubbooks_bookclubmembers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclubmembers',
            name='is_mod',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InviteURL',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('book_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookclub')),
            ],
        ),
    ]
